services:
  mcp-gateway:
    image: docker/mcp-gateway:v0.44.1
    command:
      - --servers=github-official
      - --transport=streaming
      - --port=8811      
#      - --servers=slack
#      - --servers=kubernetes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8811:8811"
    secrets:
      - mcp_secrets
secrets:
  mcp_secrets:
    file: ./mcp-secrets.env
