services:
  client:
    build: .
    environment:
      - MCP_HOST=http://gateway:8811/mcp
    depends_on:
      - gateway
    restart: on-failure

  gateway:
    image: docker/mcp-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --transport=streaming
      - --servers=SQLite
      - --port=8811
      - --verbose=false

  db-init:
    image: mcp/sqlite@sha256:efbc05ccace18df122f26b674bd1730c76ece716551df2b3961d519909c34696
    volumes:
      - ./data:/mcp
    entrypoint: ["sh", "-c", "exit 0"]
